### ISSUE TITLE
Thank you for forking and maintaining this extension

### ISSUE THREAD

**Issue by mrchrisadams** [Christoph-Wagner/firefox-better-history-ng#14]
No issues, or requests for changes - I just wanted to say thank you for forking and maintaining this plugin, because open source maintainence can be a thankless thing, and I figured others might feel the same way too.

Vivaldi's search is one of the best things about the browser, but otherwise I'd much prefer to keep using Firefox, and this plugin makes that decision easier to take.

Discovering this plugin today made my day - awesome work 👍

**Comment by Christoph-Wagner** [comment]
Happy to help, I mainly forked this for myself, which is also why I’ll hope I’ll eventually manage to investigate the current performance issues that can happen :D
