### ISSUE TITLE
[feature request] opening all tabs of one given day

### ISSUE THREAD

**Issue by DeltaGarnet** [Christoph-Wagner/firefox-better-history-ng#16]
It would be cool to be able to click a day, and it opens all results corresponding to the query. I don't know if others would also benefit from this so I'm putting that here

**Comment by Christoph-Wagner** [comment]
What do you mean, open all links of the result in a new tab?

**Comment by DeltaGarnet** [comment]
In multiple tabs. Say I searched for youtube and had multiple results from yesterday. Then I would want to open all these tabs up (probably by simply clicking the day, very intuitively) so I could copy the urls or further search in them.

So opening all the search results of a day, each in a different tab, by clicking on the day

**Comment by DeltaGarnet** [comment]
works beautifully thank you
